# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.network "forwarded_port", guest: 8080, host: 3000

  config.vm.synced_folder "./shared-folder", "/Users/igorgulyaschy/Desktop/IITmax/lab1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "nodejs-app"
    vb.gui = true
    vb.memory = "512"
  end

  config.vm.provision "script", type: "shell", privileged: false do |s|
    s.path = "./script.sh"
  end
end
